// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/api/handlers/records_handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/frolmr/GophKeeper/internal/server/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRecordsRepository is a mock of RecordsRepository interface.
type MockRecordsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecordsRepositoryMockRecorder
}

// MockRecordsRepositoryMockRecorder is the mock recorder for MockRecordsRepository.
type MockRecordsRepositoryMockRecorder struct {
	mock *MockRecordsRepository
}

// NewMockRecordsRepository creates a new mock instance.
func NewMockRecordsRepository(ctrl *gomock.Controller) *MockRecordsRepository {
	mock := &MockRecordsRepository{ctrl: ctrl}
	mock.recorder = &MockRecordsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordsRepository) EXPECT() *MockRecordsRepositoryMockRecorder {
	return m.recorder
}

// AddRecord mocks base method.
func (m *MockRecordsRepository) AddRecord(ctx context.Context, name, kind string, payload, metadata []byte, userUUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecord", ctx, name, kind, payload, metadata, userUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRecord indicates an expected call of AddRecord.
func (mr *MockRecordsRepositoryMockRecorder) AddRecord(ctx, name, kind, payload, metadata, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecord", reflect.TypeOf((*MockRecordsRepository)(nil).AddRecord), ctx, name, kind, payload, metadata, userUUID)
}

// DeleteRecord mocks base method.
func (m *MockRecordsRepository) DeleteRecord(ctx context.Context, recordUUID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecord", ctx, recordUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecord indicates an expected call of DeleteRecord.
func (mr *MockRecordsRepositoryMockRecorder) DeleteRecord(ctx, recordUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecord", reflect.TypeOf((*MockRecordsRepository)(nil).DeleteRecord), ctx, recordUUID)
}

// GetAllUserRecords mocks base method.
func (m *MockRecordsRepository) GetAllUserRecords(ctx context.Context, userUUID uuid.UUID) ([]*domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserRecords", ctx, userUUID)
	ret0, _ := ret[0].([]*domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserRecords indicates an expected call of GetAllUserRecords.
func (mr *MockRecordsRepositoryMockRecorder) GetAllUserRecords(ctx, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserRecords", reflect.TypeOf((*MockRecordsRepository)(nil).GetAllUserRecords), ctx, userUUID)
}

// GetRecordByUserUUIDAndUUID mocks base method.
func (m *MockRecordsRepository) GetRecordByUserUUIDAndUUID(ctx context.Context, recordUUID, userUUID uuid.UUID) (*domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordByUserUUIDAndUUID", ctx, recordUUID, userUUID)
	ret0, _ := ret[0].(*domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordByUserUUIDAndUUID indicates an expected call of GetRecordByUserUUIDAndUUID.
func (mr *MockRecordsRepositoryMockRecorder) GetRecordByUserUUIDAndUUID(ctx, recordUUID, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordByUserUUIDAndUUID", reflect.TypeOf((*MockRecordsRepository)(nil).GetRecordByUserUUIDAndUUID), ctx, recordUUID, userUUID)
}

// UpdateRecord mocks base method.
func (m *MockRecordsRepository) UpdateRecord(ctx context.Context, record *domain.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecord indicates an expected call of UpdateRecord.
func (mr *MockRecordsRepositoryMockRecorder) UpdateRecord(ctx, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecord", reflect.TypeOf((*MockRecordsRepository)(nil).UpdateRecord), ctx, record)
}
