// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/api/handlers/devices_handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/frolmr/GophKeeper/internal/server/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockDevicesRepository is a mock of DevicesRepository interface.
type MockDevicesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDevicesRepositoryMockRecorder
}

// MockDevicesRepositoryMockRecorder is the mock recorder for MockDevicesRepository.
type MockDevicesRepositoryMockRecorder struct {
	mock *MockDevicesRepository
}

// NewMockDevicesRepository creates a new mock instance.
func NewMockDevicesRepository(ctrl *gomock.Controller) *MockDevicesRepository {
	mock := &MockDevicesRepository{ctrl: ctrl}
	mock.recorder = &MockDevicesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDevicesRepository) EXPECT() *MockDevicesRepositoryMockRecorder {
	return m.recorder
}

// AddDevice mocks base method.
func (m *MockDevicesRepository) AddDevice(ctx context.Context, name, id string, pk []byte, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDevice", ctx, name, id, pk, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevice indicates an expected call of AddDevice.
func (mr *MockDevicesRepositoryMockRecorder) AddDevice(ctx, name, id, pk, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevice", reflect.TypeOf((*MockDevicesRepository)(nil).AddDevice), ctx, name, id, pk, user)
}

// ConfirmDevice mocks base method.
func (m *MockDevicesRepository) ConfirmDevice(ctx context.Context, deviceUUID, userUUID uuid.UUID, mk []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmDevice", ctx, deviceUUID, userUUID, mk)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmDevice indicates an expected call of ConfirmDevice.
func (mr *MockDevicesRepositoryMockRecorder) ConfirmDevice(ctx, deviceUUID, userUUID, mk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmDevice", reflect.TypeOf((*MockDevicesRepository)(nil).ConfirmDevice), ctx, deviceUUID, userUUID, mk)
}

// GetAllUserDevices mocks base method.
func (m *MockDevicesRepository) GetAllUserDevices(ctx context.Context, userUUID uuid.UUID) ([]*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserDevices", ctx, userUUID)
	ret0, _ := ret[0].([]*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserDevices indicates an expected call of GetAllUserDevices.
func (mr *MockDevicesRepositoryMockRecorder) GetAllUserDevices(ctx, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserDevices", reflect.TypeOf((*MockDevicesRepository)(nil).GetAllUserDevices), ctx, userUUID)
}

// GetDeviceByUserUUIDAndID mocks base method.
func (m *MockDevicesRepository) GetDeviceByUserUUIDAndID(ctx context.Context, id string, userUUID uuid.UUID) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByUserUUIDAndID", ctx, id, userUUID)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByUserUUIDAndID indicates an expected call of GetDeviceByUserUUIDAndID.
func (mr *MockDevicesRepositoryMockRecorder) GetDeviceByUserUUIDAndID(ctx, id, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByUserUUIDAndID", reflect.TypeOf((*MockDevicesRepository)(nil).GetDeviceByUserUUIDAndID), ctx, id, userUUID)
}

// GetDeviceByUserUUIDAndUUID mocks base method.
func (m *MockDevicesRepository) GetDeviceByUserUUIDAndUUID(ctx context.Context, deviceUUID, userUUID uuid.UUID) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByUserUUIDAndUUID", ctx, deviceUUID, userUUID)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByUserUUIDAndUUID indicates an expected call of GetDeviceByUserUUIDAndUUID.
func (mr *MockDevicesRepositoryMockRecorder) GetDeviceByUserUUIDAndUUID(ctx, deviceUUID, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByUserUUIDAndUUID", reflect.TypeOf((*MockDevicesRepository)(nil).GetDeviceByUserUUIDAndUUID), ctx, deviceUUID, userUUID)
}
