// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/proto/users/users.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Mk            []byte                 `protobuf:"bytes,5,opt,name=mk" json:"mk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_pkg_proto_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetMk() []byte {
	if x != nil {
		return x.Mk
	}
	return nil
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_pkg_proto_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

var File_pkg_proto_users_users_proto protoreflect.FileDescriptor

const file_pkg_proto_users_users_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/users/users.proto\x12\x05users\x1a\x1bgoogle/protobuf/empty.proto\"W\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02mk\x18\x05 \x01(\fR\x02mk\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\x89\x01\n" +
	"\x05Users\x12B\n" +
	"\fRegisterUser\x12\x1a.users.RegisterUserRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\tLoginUser\x12\x17.users.LoginUserRequest\x1a\x16.google.protobuf.EmptyB\rZ\vusers/protob\beditionsp\xe8\a"

var (
	file_pkg_proto_users_users_proto_rawDescOnce sync.Once
	file_pkg_proto_users_users_proto_rawDescData []byte
)

func file_pkg_proto_users_users_proto_rawDescGZIP() []byte {
	file_pkg_proto_users_users_proto_rawDescOnce.Do(func() {
		file_pkg_proto_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_users_users_proto_rawDesc), len(file_pkg_proto_users_users_proto_rawDesc)))
	})
	return file_pkg_proto_users_users_proto_rawDescData
}

var file_pkg_proto_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_users_users_proto_goTypes = []any{
	(*RegisterUserRequest)(nil), // 0: users.RegisterUserRequest
	(*LoginUserRequest)(nil),    // 1: users.LoginUserRequest
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
}
var file_pkg_proto_users_users_proto_depIdxs = []int32{
	0, // 0: users.Users.RegisterUser:input_type -> users.RegisterUserRequest
	1, // 1: users.Users.LoginUser:input_type -> users.LoginUserRequest
	2, // 2: users.Users.RegisterUser:output_type -> google.protobuf.Empty
	2, // 3: users.Users.LoginUser:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_users_users_proto_init() }
func file_pkg_proto_users_users_proto_init() {
	if File_pkg_proto_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_users_users_proto_rawDesc), len(file_pkg_proto_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_users_users_proto_goTypes,
		DependencyIndexes: file_pkg_proto_users_users_proto_depIdxs,
		MessageInfos:      file_pkg_proto_users_users_proto_msgTypes,
	}.Build()
	File_pkg_proto_users_users_proto = out.File
	file_pkg_proto_users_users_proto_goTypes = nil
	file_pkg_proto_users_users_proto_depIdxs = nil
}
