// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/proto/users/users.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Mk            []byte                 `protobuf:"bytes,3,opt,name=mk" json:"mk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_pkg_proto_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetMk() []byte {
	if x != nil {
		return x.Mk
	}
	return nil
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_pkg_proto_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type AddDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mk            []byte                 `protobuf:"bytes,2,opt,name=mk" json:"mk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDeviceRequest) Reset() {
	*x = AddDeviceRequest{}
	mi := &file_pkg_proto_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceRequest) ProtoMessage() {}

func (x *AddDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceRequest.ProtoReflect.Descriptor instead.
func (*AddDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *AddDeviceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AddDeviceRequest) GetMk() []byte {
	if x != nil {
		return x.Mk
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      *bool                  `protobuf:"varint,1,opt,name=received" json:"received,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pkg_proto_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetReceived() bool {
	if x != nil && x.Received != nil {
		return *x.Received
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_pkg_proto_users_users_proto protoreflect.FileDescriptor

const file_pkg_proto_users_users_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/users/users.proto\x12\x05users\"W\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02mk\x18\x03 \x01(\fR\x02mk\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"6\n" +
	"\x10AddDeviceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02mk\x18\x02 \x01(\fR\x02mk\"7\n" +
	"\x03Ack\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa3\x01\n" +
	"\x05Users\x126\n" +
	"\fRegisterUser\x12\x1a.users.RegisterUserRequest\x1a\n" +
	".users.Ack\x120\n" +
	"\tLoginUser\x12\x17.users.LoginUserRequest\x1a\n" +
	".users.Ack\x120\n" +
	"\tAddDevice\x12\x17.users.AddDeviceRequest\x1a\n" +
	".users.AckB\rZ\vusers/protob\beditionsp\xe8\a"

var (
	file_pkg_proto_users_users_proto_rawDescOnce sync.Once
	file_pkg_proto_users_users_proto_rawDescData []byte
)

func file_pkg_proto_users_users_proto_rawDescGZIP() []byte {
	file_pkg_proto_users_users_proto_rawDescOnce.Do(func() {
		file_pkg_proto_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_users_users_proto_rawDesc), len(file_pkg_proto_users_users_proto_rawDesc)))
	})
	return file_pkg_proto_users_users_proto_rawDescData
}

var file_pkg_proto_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_users_users_proto_goTypes = []any{
	(*RegisterUserRequest)(nil), // 0: users.RegisterUserRequest
	(*LoginUserRequest)(nil),    // 1: users.LoginUserRequest
	(*AddDeviceRequest)(nil),    // 2: users.AddDeviceRequest
	(*Ack)(nil),                 // 3: users.Ack
}
var file_pkg_proto_users_users_proto_depIdxs = []int32{
	0, // 0: users.Users.RegisterUser:input_type -> users.RegisterUserRequest
	1, // 1: users.Users.LoginUser:input_type -> users.LoginUserRequest
	2, // 2: users.Users.AddDevice:input_type -> users.AddDeviceRequest
	3, // 3: users.Users.RegisterUser:output_type -> users.Ack
	3, // 4: users.Users.LoginUser:output_type -> users.Ack
	3, // 5: users.Users.AddDevice:output_type -> users.Ack
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_users_users_proto_init() }
func file_pkg_proto_users_users_proto_init() {
	if File_pkg_proto_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_users_users_proto_rawDesc), len(file_pkg_proto_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_users_users_proto_goTypes,
		DependencyIndexes: file_pkg_proto_users_users_proto_depIdxs,
		MessageInfos:      file_pkg_proto_users_users_proto_msgTypes,
	}.Build()
	File_pkg_proto_users_users_proto = out.File
	file_pkg_proto_users_users_proto_goTypes = nil
	file_pkg_proto_users_users_proto_depIdxs = nil
}
