// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/api/interceptors/device_interceptor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/frolmr/GophKeeper/internal/server/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockDeviceRepository is a mock of DeviceRepository interface.
type MockDeviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRepositoryMockRecorder
}

// MockDeviceRepositoryMockRecorder is the mock recorder for MockDeviceRepository.
type MockDeviceRepositoryMockRecorder struct {
	mock *MockDeviceRepository
}

// NewMockDeviceRepository creates a new mock instance.
func NewMockDeviceRepository(ctrl *gomock.Controller) *MockDeviceRepository {
	mock := &MockDeviceRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRepository) EXPECT() *MockDeviceRepositoryMockRecorder {
	return m.recorder
}

// GetDeviceByUserUUIDAndID mocks base method.
func (m *MockDeviceRepository) GetDeviceByUserUUIDAndID(ctx context.Context, id string, userUUID uuid.UUID) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByUserUUIDAndID", ctx, id, userUUID)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByUserUUIDAndID indicates an expected call of GetDeviceByUserUUIDAndID.
func (mr *MockDeviceRepositoryMockRecorder) GetDeviceByUserUUIDAndID(ctx, id, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByUserUUIDAndID", reflect.TypeOf((*MockDeviceRepository)(nil).GetDeviceByUserUUIDAndID), ctx, id, userUUID)
}
