// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/proto/devices/devices.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Confirmed     *bool                  `protobuf:"varint,3,opt,name=confirmed" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_pkg_proto_devices_devices_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Device) GetConfirmed() bool {
	if x != nil && x.Confirmed != nil {
		return *x.Confirmed
	}
	return false
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_devices_devices_proto_rawDescGZIP(), []int{1}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_devices_devices_proto_rawDescGZIP(), []int{2}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type AddDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pk            []byte                 `protobuf:"bytes,3,opt,name=pk" json:"pk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDeviceRequest) Reset() {
	*x = AddDeviceRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceRequest) ProtoMessage() {}

func (x *AddDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceRequest.ProtoReflect.Descriptor instead.
func (*AddDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_devices_devices_proto_rawDescGZIP(), []int{3}
}

func (x *AddDeviceRequest) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

type GetDevicePKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicePKRequest) Reset() {
	*x = GetDevicePKRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicePKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicePKRequest) ProtoMessage() {}

func (x *GetDevicePKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicePKRequest.ProtoReflect.Descriptor instead.
func (*GetDevicePKRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_devices_devices_proto_rawDescGZIP(), []int{4}
}

func (x *GetDevicePKRequest) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

type GetDevicePKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pk            []byte                 `protobuf:"bytes,2,opt,name=pk" json:"pk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicePKResponse) Reset() {
	*x = GetDevicePKResponse{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicePKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicePKResponse) ProtoMessage() {}

func (x *GetDevicePKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicePKResponse.ProtoReflect.Descriptor instead.
func (*GetDevicePKResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_devices_devices_proto_rawDescGZIP(), []int{5}
}

func (x *GetDevicePKResponse) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

type GetDeviceMKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceMKRequest) Reset() {
	*x = GetDeviceMKRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceMKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceMKRequest) ProtoMessage() {}

func (x *GetDeviceMKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceMKRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceMKRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_devices_devices_proto_rawDescGZIP(), []int{6}
}

type GetDeviceMKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mk            []byte                 `protobuf:"bytes,1,opt,name=mk" json:"mk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceMKResponse) Reset() {
	*x = GetDeviceMKResponse{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceMKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceMKResponse) ProtoMessage() {}

func (x *GetDeviceMKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceMKResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceMKResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_devices_devices_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceMKResponse) GetMk() []byte {
	if x != nil {
		return x.Mk
	}
	return nil
}

type ApproveDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Mk            []byte                 `protobuf:"bytes,2,opt,name=mk" json:"mk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveDeviceRequest) Reset() {
	*x = ApproveDeviceRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveDeviceRequest) ProtoMessage() {}

func (x *ApproveDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveDeviceRequest.ProtoReflect.Descriptor instead.
func (*ApproveDeviceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_devices_devices_proto_rawDescGZIP(), []int{8}
}

func (x *ApproveDeviceRequest) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *ApproveDeviceRequest) GetMk() []byte {
	if x != nil {
		return x.Mk
	}
	return nil
}

var File_pkg_proto_devices_devices_proto protoreflect.FileDescriptor

const file_pkg_proto_devices_devices_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/devices/devices.proto\x12\adevices\x1a\x1bgoogle/protobuf/empty.proto\"N\n" +
	"\x06Device\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tconfirmed\x18\x03 \x01(\bR\tconfirmed\"\x14\n" +
	"\x12ListDevicesRequest\"@\n" +
	"\x13ListDevicesResponse\x12)\n" +
	"\adevices\x18\x01 \x03(\v2\x0f.devices.DeviceR\adevices\"\"\n" +
	"\x10AddDeviceRequest\x12\x0e\n" +
	"\x02pk\x18\x03 \x01(\fR\x02pk\"(\n" +
	"\x12GetDevicePKRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"%\n" +
	"\x13GetDevicePKResponse\x12\x0e\n" +
	"\x02pk\x18\x02 \x01(\fR\x02pk\"\x14\n" +
	"\x12GetDeviceMKRequest\"%\n" +
	"\x13GetDeviceMKResponse\x12\x0e\n" +
	"\x02mk\x18\x01 \x01(\fR\x02mk\":\n" +
	"\x14ApproveDeviceRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x0e\n" +
	"\x02mk\x18\x02 \x01(\fR\x02mk2\xef\x02\n" +
	"\aDevices\x12H\n" +
	"\vListDevices\x12\x1b.devices.ListDevicesRequest\x1a\x1c.devices.ListDevicesResponse\x12H\n" +
	"\vGetDevicePK\x12\x1b.devices.GetDevicePKRequest\x1a\x1c.devices.GetDevicePKResponse\x12H\n" +
	"\vGetDeviceMK\x12\x1b.devices.GetDeviceMKRequest\x1a\x1c.devices.GetDeviceMKResponse\x12>\n" +
	"\tAddDevice\x12\x19.devices.AddDeviceRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\rApproveDevice\x12\x1d.devices.ApproveDeviceRequest\x1a\x16.google.protobuf.EmptyB\x0fZ\rdevices/protob\beditionsp\xe8\a"

var (
	file_pkg_proto_devices_devices_proto_rawDescOnce sync.Once
	file_pkg_proto_devices_devices_proto_rawDescData []byte
)

func file_pkg_proto_devices_devices_proto_rawDescGZIP() []byte {
	file_pkg_proto_devices_devices_proto_rawDescOnce.Do(func() {
		file_pkg_proto_devices_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_devices_devices_proto_rawDesc), len(file_pkg_proto_devices_devices_proto_rawDesc)))
	})
	return file_pkg_proto_devices_devices_proto_rawDescData
}

var file_pkg_proto_devices_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_devices_devices_proto_goTypes = []any{
	(*Device)(nil),               // 0: devices.Device
	(*ListDevicesRequest)(nil),   // 1: devices.ListDevicesRequest
	(*ListDevicesResponse)(nil),  // 2: devices.ListDevicesResponse
	(*AddDeviceRequest)(nil),     // 3: devices.AddDeviceRequest
	(*GetDevicePKRequest)(nil),   // 4: devices.GetDevicePKRequest
	(*GetDevicePKResponse)(nil),  // 5: devices.GetDevicePKResponse
	(*GetDeviceMKRequest)(nil),   // 6: devices.GetDeviceMKRequest
	(*GetDeviceMKResponse)(nil),  // 7: devices.GetDeviceMKResponse
	(*ApproveDeviceRequest)(nil), // 8: devices.ApproveDeviceRequest
	(*emptypb.Empty)(nil),        // 9: google.protobuf.Empty
}
var file_pkg_proto_devices_devices_proto_depIdxs = []int32{
	0, // 0: devices.ListDevicesResponse.devices:type_name -> devices.Device
	1, // 1: devices.Devices.ListDevices:input_type -> devices.ListDevicesRequest
	4, // 2: devices.Devices.GetDevicePK:input_type -> devices.GetDevicePKRequest
	6, // 3: devices.Devices.GetDeviceMK:input_type -> devices.GetDeviceMKRequest
	3, // 4: devices.Devices.AddDevice:input_type -> devices.AddDeviceRequest
	8, // 5: devices.Devices.ApproveDevice:input_type -> devices.ApproveDeviceRequest
	2, // 6: devices.Devices.ListDevices:output_type -> devices.ListDevicesResponse
	5, // 7: devices.Devices.GetDevicePK:output_type -> devices.GetDevicePKResponse
	7, // 8: devices.Devices.GetDeviceMK:output_type -> devices.GetDeviceMKResponse
	9, // 9: devices.Devices.AddDevice:output_type -> google.protobuf.Empty
	9, // 10: devices.Devices.ApproveDevice:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_devices_devices_proto_init() }
func file_pkg_proto_devices_devices_proto_init() {
	if File_pkg_proto_devices_devices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_devices_devices_proto_rawDesc), len(file_pkg_proto_devices_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_devices_devices_proto_goTypes,
		DependencyIndexes: file_pkg_proto_devices_devices_proto_depIdxs,
		MessageInfos:      file_pkg_proto_devices_devices_proto_msgTypes,
	}.Build()
	File_pkg_proto_devices_devices_proto = out.File
	file_pkg_proto_devices_devices_proto_goTypes = nil
	file_pkg_proto_devices_devices_proto_depIdxs = nil
}
