// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/proto/devices/devices.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uuid        *string                `protobuf:"bytes,1,opt,name=uuid"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Confirmed   bool                   `protobuf:"varint,3,opt,name=confirmed"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Device) GetUuid() string {
	if x != nil {
		if x.xxx_hidden_Uuid != nil {
			return *x.xxx_hidden_Uuid
		}
		return ""
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Device) GetConfirmed() bool {
	if x != nil {
		return x.xxx_hidden_Confirmed
	}
	return false
}

func (x *Device) SetUuid(v string) {
	x.xxx_hidden_Uuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Device) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Device) SetConfirmed(v bool) {
	x.xxx_hidden_Confirmed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Device) HasUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Device) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Device) HasConfirmed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Device) ClearUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Uuid = nil
}

func (x *Device) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Device) ClearConfirmed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Confirmed = false
}

type Device_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uuid      *string
	Name      *string
	Confirmed *bool
}

func (b0 Device_builder) Build() *Device {
	m0 := &Device{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Uuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Uuid = b.Uuid
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.Confirmed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Confirmed = *b.Confirmed
	}
	return m0
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListDevicesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListDevicesRequest_builder) Build() *ListDevicesRequest {
	m0 := &ListDevicesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListDevicesResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Devices *[]*Device             `protobuf:"bytes,1,rep,name=devices"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		if x.xxx_hidden_Devices != nil {
			return *x.xxx_hidden_Devices
		}
	}
	return nil
}

func (x *ListDevicesResponse) SetDevices(v []*Device) {
	x.xxx_hidden_Devices = &v
}

type ListDevicesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Devices []*Device
}

func (b0 ListDevicesResponse_builder) Build() *ListDevicesResponse {
	m0 := &ListDevicesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Devices = &b.Devices
	return m0
}

type AddDeviceRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pk          []byte                 `protobuf:"bytes,3,opt,name=pk"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddDeviceRequest) Reset() {
	*x = AddDeviceRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceRequest) ProtoMessage() {}

func (x *AddDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddDeviceRequest) GetPk() []byte {
	if x != nil {
		return x.xxx_hidden_Pk
	}
	return nil
}

func (x *AddDeviceRequest) SetPk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Pk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AddDeviceRequest) HasPk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddDeviceRequest) ClearPk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Pk = nil
}

type AddDeviceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pk []byte
}

func (b0 AddDeviceRequest_builder) Build() *AddDeviceRequest {
	m0 := &AddDeviceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Pk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Pk = b.Pk
	}
	return m0
}

type GetDevicePKRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uuid        *string                `protobuf:"bytes,1,opt,name=uuid"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetDevicePKRequest) Reset() {
	*x = GetDevicePKRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicePKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicePKRequest) ProtoMessage() {}

func (x *GetDevicePKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetDevicePKRequest) GetUuid() string {
	if x != nil {
		if x.xxx_hidden_Uuid != nil {
			return *x.xxx_hidden_Uuid
		}
		return ""
	}
	return ""
}

func (x *GetDevicePKRequest) SetUuid(v string) {
	x.xxx_hidden_Uuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetDevicePKRequest) HasUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetDevicePKRequest) ClearUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Uuid = nil
}

type GetDevicePKRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uuid *string
}

func (b0 GetDevicePKRequest_builder) Build() *GetDevicePKRequest {
	m0 := &GetDevicePKRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Uuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Uuid = b.Uuid
	}
	return m0
}

type GetDevicePKResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pk          []byte                 `protobuf:"bytes,2,opt,name=pk"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetDevicePKResponse) Reset() {
	*x = GetDevicePKResponse{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicePKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicePKResponse) ProtoMessage() {}

func (x *GetDevicePKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetDevicePKResponse) GetPk() []byte {
	if x != nil {
		return x.xxx_hidden_Pk
	}
	return nil
}

func (x *GetDevicePKResponse) SetPk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Pk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetDevicePKResponse) HasPk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetDevicePKResponse) ClearPk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Pk = nil
}

type GetDevicePKResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pk []byte
}

func (b0 GetDevicePKResponse_builder) Build() *GetDevicePKResponse {
	m0 := &GetDevicePKResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Pk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Pk = b.Pk
	}
	return m0
}

type GetDeviceMKRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceMKRequest) Reset() {
	*x = GetDeviceMKRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceMKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceMKRequest) ProtoMessage() {}

func (x *GetDeviceMKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetDeviceMKRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetDeviceMKRequest_builder) Build() *GetDeviceMKRequest {
	m0 := &GetDeviceMKRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetDeviceMKResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Mk          []byte                 `protobuf:"bytes,1,opt,name=mk"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetDeviceMKResponse) Reset() {
	*x = GetDeviceMKResponse{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceMKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceMKResponse) ProtoMessage() {}

func (x *GetDeviceMKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetDeviceMKResponse) GetMk() []byte {
	if x != nil {
		return x.xxx_hidden_Mk
	}
	return nil
}

func (x *GetDeviceMKResponse) SetMk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Mk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetDeviceMKResponse) HasMk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetDeviceMKResponse) ClearMk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Mk = nil
}

type GetDeviceMKResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Mk []byte
}

func (b0 GetDeviceMKResponse_builder) Build() *GetDeviceMKResponse {
	m0 := &GetDeviceMKResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Mk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Mk = b.Mk
	}
	return m0
}

type ApproveDeviceRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uuid        *string                `protobuf:"bytes,1,opt,name=uuid"`
	xxx_hidden_Mk          []byte                 `protobuf:"bytes,2,opt,name=mk"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ApproveDeviceRequest) Reset() {
	*x = ApproveDeviceRequest{}
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveDeviceRequest) ProtoMessage() {}

func (x *ApproveDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_devices_devices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ApproveDeviceRequest) GetUuid() string {
	if x != nil {
		if x.xxx_hidden_Uuid != nil {
			return *x.xxx_hidden_Uuid
		}
		return ""
	}
	return ""
}

func (x *ApproveDeviceRequest) GetMk() []byte {
	if x != nil {
		return x.xxx_hidden_Mk
	}
	return nil
}

func (x *ApproveDeviceRequest) SetUuid(v string) {
	x.xxx_hidden_Uuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ApproveDeviceRequest) SetMk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Mk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ApproveDeviceRequest) HasUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ApproveDeviceRequest) HasMk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ApproveDeviceRequest) ClearUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Uuid = nil
}

func (x *ApproveDeviceRequest) ClearMk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Mk = nil
}

type ApproveDeviceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uuid *string
	Mk   []byte
}

func (b0 ApproveDeviceRequest_builder) Build() *ApproveDeviceRequest {
	m0 := &ApproveDeviceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Uuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Uuid = b.Uuid
	}
	if b.Mk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Mk = b.Mk
	}
	return m0
}

var File_pkg_proto_devices_devices_proto protoreflect.FileDescriptor

const file_pkg_proto_devices_devices_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/devices/devices.proto\x12\adevices\x1a\x1bgoogle/protobuf/empty.proto\x1a!google/protobuf/go_features.proto\"N\n" +
	"\x06Device\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tconfirmed\x18\x03 \x01(\bR\tconfirmed\"\x14\n" +
	"\x12ListDevicesRequest\"@\n" +
	"\x13ListDevicesResponse\x12)\n" +
	"\adevices\x18\x01 \x03(\v2\x0f.devices.DeviceR\adevices\"\"\n" +
	"\x10AddDeviceRequest\x12\x0e\n" +
	"\x02pk\x18\x03 \x01(\fR\x02pk\"(\n" +
	"\x12GetDevicePKRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"%\n" +
	"\x13GetDevicePKResponse\x12\x0e\n" +
	"\x02pk\x18\x02 \x01(\fR\x02pk\"\x14\n" +
	"\x12GetDeviceMKRequest\"%\n" +
	"\x13GetDeviceMKResponse\x12\x0e\n" +
	"\x02mk\x18\x01 \x01(\fR\x02mk\":\n" +
	"\x14ApproveDeviceRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x0e\n" +
	"\x02mk\x18\x02 \x01(\fR\x02mk2\xef\x02\n" +
	"\aDevices\x12H\n" +
	"\vListDevices\x12\x1b.devices.ListDevicesRequest\x1a\x1c.devices.ListDevicesResponse\x12H\n" +
	"\vGetDevicePK\x12\x1b.devices.GetDevicePKRequest\x1a\x1c.devices.GetDevicePKResponse\x12H\n" +
	"\vGetDeviceMK\x12\x1b.devices.GetDeviceMKRequest\x1a\x1c.devices.GetDeviceMKResponse\x12>\n" +
	"\tAddDevice\x12\x19.devices.AddDeviceRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\rApproveDevice\x12\x1d.devices.ApproveDeviceRequest\x1a\x16.google.protobuf.EmptyB\x17Z\rdevices/proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_pkg_proto_devices_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_devices_devices_proto_goTypes = []any{
	(*Device)(nil),               // 0: devices.Device
	(*ListDevicesRequest)(nil),   // 1: devices.ListDevicesRequest
	(*ListDevicesResponse)(nil),  // 2: devices.ListDevicesResponse
	(*AddDeviceRequest)(nil),     // 3: devices.AddDeviceRequest
	(*GetDevicePKRequest)(nil),   // 4: devices.GetDevicePKRequest
	(*GetDevicePKResponse)(nil),  // 5: devices.GetDevicePKResponse
	(*GetDeviceMKRequest)(nil),   // 6: devices.GetDeviceMKRequest
	(*GetDeviceMKResponse)(nil),  // 7: devices.GetDeviceMKResponse
	(*ApproveDeviceRequest)(nil), // 8: devices.ApproveDeviceRequest
	(*emptypb.Empty)(nil),        // 9: google.protobuf.Empty
}
var file_pkg_proto_devices_devices_proto_depIdxs = []int32{
	0, // 0: devices.ListDevicesResponse.devices:type_name -> devices.Device
	1, // 1: devices.Devices.ListDevices:input_type -> devices.ListDevicesRequest
	4, // 2: devices.Devices.GetDevicePK:input_type -> devices.GetDevicePKRequest
	6, // 3: devices.Devices.GetDeviceMK:input_type -> devices.GetDeviceMKRequest
	3, // 4: devices.Devices.AddDevice:input_type -> devices.AddDeviceRequest
	8, // 5: devices.Devices.ApproveDevice:input_type -> devices.ApproveDeviceRequest
	2, // 6: devices.Devices.ListDevices:output_type -> devices.ListDevicesResponse
	5, // 7: devices.Devices.GetDevicePK:output_type -> devices.GetDevicePKResponse
	7, // 8: devices.Devices.GetDeviceMK:output_type -> devices.GetDeviceMKResponse
	9, // 9: devices.Devices.AddDevice:output_type -> google.protobuf.Empty
	9, // 10: devices.Devices.ApproveDevice:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_devices_devices_proto_init() }
func file_pkg_proto_devices_devices_proto_init() {
	if File_pkg_proto_devices_devices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_devices_devices_proto_rawDesc), len(file_pkg_proto_devices_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_devices_devices_proto_goTypes,
		DependencyIndexes: file_pkg_proto_devices_devices_proto_depIdxs,
		MessageInfos:      file_pkg_proto_devices_devices_proto_msgTypes,
	}.Build()
	File_pkg_proto_devices_devices_proto = out.File
	file_pkg_proto_devices_devices_proto_goTypes = nil
	file_pkg_proto_devices_devices_proto_depIdxs = nil
}
