// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/app/user/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	rsa "crypto/rsa"
	reflect "reflect"

	crypto "github.com/frolmr/GophKeeper/internal/client/crypto"
	gomock "github.com/golang/mock/gomock"
)

// MockConnector is a mock of Connector interface.
type MockConnector struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorMockRecorder
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder struct {
	mock *MockConnector
}

// NewMockConnector creates a new mock instance.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	mock := &MockConnector{ctrl: ctrl}
	mock.recorder = &MockConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnector) EXPECT() *MockConnectorMockRecorder {
	return m.recorder
}

// SendLoginRequest mocks base method.
func (m *MockConnector) SendLoginRequest(email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLoginRequest", email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLoginRequest indicates an expected call of SendLoginRequest.
func (mr *MockConnectorMockRecorder) SendLoginRequest(email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLoginRequest", reflect.TypeOf((*MockConnector)(nil).SendLoginRequest), email, password)
}

// SendRegisterRequest mocks base method.
func (m *MockConnector) SendRegisterRequest(email, password string, mk []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRegisterRequest", email, password, mk)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRegisterRequest indicates an expected call of SendRegisterRequest.
func (mr *MockConnectorMockRecorder) SendRegisterRequest(email, password, mk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRegisterRequest", reflect.TypeOf((*MockConnector)(nil).SendRegisterRequest), email, password, mk)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ReadPrivateKey mocks base method.
func (m *MockRepository) ReadPrivateKey() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPrivateKey")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPrivateKey indicates an expected call of ReadPrivateKey.
func (mr *MockRepositoryMockRecorder) ReadPrivateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPrivateKey", reflect.TypeOf((*MockRepository)(nil).ReadPrivateKey))
}

// SavePrivateKey mocks base method.
func (m *MockRepository) SavePrivateKey(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePrivateKey", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePrivateKey indicates an expected call of SavePrivateKey.
func (mr *MockRepositoryMockRecorder) SavePrivateKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePrivateKey", reflect.TypeOf((*MockRepository)(nil).SavePrivateKey), arg0)
}

// SaveToken mocks base method.
func (m *MockRepository) SaveToken(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockRepositoryMockRecorder) SaveToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockRepository)(nil).SaveToken), arg0)
}

// MockCryptoProcessor is a mock of CryptoProcessor interface.
type MockCryptoProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockCryptoProcessorMockRecorder
}

// MockCryptoProcessorMockRecorder is the mock recorder for MockCryptoProcessor.
type MockCryptoProcessorMockRecorder struct {
	mock *MockCryptoProcessor
}

// NewMockCryptoProcessor creates a new mock instance.
func NewMockCryptoProcessor(ctrl *gomock.Controller) *MockCryptoProcessor {
	mock := &MockCryptoProcessor{ctrl: ctrl}
	mock.recorder = &MockCryptoProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptoProcessor) EXPECT() *MockCryptoProcessorMockRecorder {
	return m.recorder
}

// BytesToPrivateKey mocks base method.
func (m *MockCryptoProcessor) BytesToPrivateKey(arg0 []byte) (*rsa.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BytesToPrivateKey", arg0)
	ret0, _ := ret[0].(*rsa.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BytesToPrivateKey indicates an expected call of BytesToPrivateKey.
func (mr *MockCryptoProcessorMockRecorder) BytesToPrivateKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesToPrivateKey", reflect.TypeOf((*MockCryptoProcessor)(nil).BytesToPrivateKey), arg0)
}

// EncryptWithPublicKey mocks base method.
func (m *MockCryptoProcessor) EncryptWithPublicKey(arg0 []byte, arg1 *rsa.PublicKey) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptWithPublicKey", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptWithPublicKey indicates an expected call of EncryptWithPublicKey.
func (mr *MockCryptoProcessorMockRecorder) EncryptWithPublicKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptWithPublicKey", reflect.TypeOf((*MockCryptoProcessor)(nil).EncryptWithPublicKey), arg0, arg1)
}

// GenerateDeviceKey mocks base method.
func (m *MockCryptoProcessor) GenerateDeviceKey() (*crypto.DeviceKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDeviceKey")
	ret0, _ := ret[0].(*crypto.DeviceKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDeviceKey indicates an expected call of GenerateDeviceKey.
func (mr *MockCryptoProcessorMockRecorder) GenerateDeviceKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDeviceKey", reflect.TypeOf((*MockCryptoProcessor)(nil).GenerateDeviceKey))
}

// GenerateMasterKey mocks base method.
func (m *MockCryptoProcessor) GenerateMasterKey() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateMasterKey")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateMasterKey indicates an expected call of GenerateMasterKey.
func (mr *MockCryptoProcessorMockRecorder) GenerateMasterKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMasterKey", reflect.TypeOf((*MockCryptoProcessor)(nil).GenerateMasterKey))
}

// PrivateKeyToBytes mocks base method.
func (m *MockCryptoProcessor) PrivateKeyToBytes(arg0 *rsa.PrivateKey) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateKeyToBytes", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrivateKeyToBytes indicates an expected call of PrivateKeyToBytes.
func (mr *MockCryptoProcessorMockRecorder) PrivateKeyToBytes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateKeyToBytes", reflect.TypeOf((*MockCryptoProcessor)(nil).PrivateKeyToBytes), arg0)
}
