// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/app/record/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	rsa "crypto/rsa"
	reflect "reflect"

	domain "github.com/frolmr/GophKeeper/internal/client/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockConnector is a mock of Connector interface.
type MockConnector struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorMockRecorder
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder struct {
	mock *MockConnector
}

// NewMockConnector creates a new mock instance.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	mock := &MockConnector{ctrl: ctrl}
	mock.recorder = &MockConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnector) EXPECT() *MockConnectorMockRecorder {
	return m.recorder
}

// SendAddRecordRequest mocks base method.
func (m *MockConnector) SendAddRecordRequest(encRec domain.EncryptedRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAddRecordRequest", encRec)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAddRecordRequest indicates an expected call of SendAddRecordRequest.
func (mr *MockConnectorMockRecorder) SendAddRecordRequest(encRec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAddRecordRequest", reflect.TypeOf((*MockConnector)(nil).SendAddRecordRequest), encRec)
}

// SendDeleteRecordRequest mocks base method.
func (m *MockConnector) SendDeleteRecordRequest(recUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDeleteRecordRequest", recUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDeleteRecordRequest indicates an expected call of SendDeleteRecordRequest.
func (mr *MockConnectorMockRecorder) SendDeleteRecordRequest(recUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDeleteRecordRequest", reflect.TypeOf((*MockConnector)(nil).SendDeleteRecordRequest), recUUID)
}

// SendGetDeviceMKRequest mocks base method.
func (m *MockConnector) SendGetDeviceMKRequest() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendGetDeviceMKRequest")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendGetDeviceMKRequest indicates an expected call of SendGetDeviceMKRequest.
func (mr *MockConnectorMockRecorder) SendGetDeviceMKRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendGetDeviceMKRequest", reflect.TypeOf((*MockConnector)(nil).SendGetDeviceMKRequest))
}

// SendGetRecordRequest mocks base method.
func (m *MockConnector) SendGetRecordRequest(recUUID string) (*domain.EncryptedRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendGetRecordRequest", recUUID)
	ret0, _ := ret[0].(*domain.EncryptedRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendGetRecordRequest indicates an expected call of SendGetRecordRequest.
func (mr *MockConnectorMockRecorder) SendGetRecordRequest(recUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendGetRecordRequest", reflect.TypeOf((*MockConnector)(nil).SendGetRecordRequest), recUUID)
}

// SendListRecordsRequest mocks base method.
func (m *MockConnector) SendListRecordsRequest() ([]domain.EncryptedRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendListRecordsRequest")
	ret0, _ := ret[0].([]domain.EncryptedRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendListRecordsRequest indicates an expected call of SendListRecordsRequest.
func (mr *MockConnectorMockRecorder) SendListRecordsRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendListRecordsRequest", reflect.TypeOf((*MockConnector)(nil).SendListRecordsRequest))
}

// SendUpdateRecordRequest mocks base method.
func (m *MockConnector) SendUpdateRecordRequest(encRec domain.EncryptedRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendUpdateRecordRequest", encRec)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendUpdateRecordRequest indicates an expected call of SendUpdateRecordRequest.
func (mr *MockConnectorMockRecorder) SendUpdateRecordRequest(encRec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUpdateRecordRequest", reflect.TypeOf((*MockConnector)(nil).SendUpdateRecordRequest), encRec)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ReadPrivateKey mocks base method.
func (m *MockRepository) ReadPrivateKey() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPrivateKey")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPrivateKey indicates an expected call of ReadPrivateKey.
func (mr *MockRepositoryMockRecorder) ReadPrivateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPrivateKey", reflect.TypeOf((*MockRepository)(nil).ReadPrivateKey))
}

// MockCryptoProcessor is a mock of CryptoProcessor interface.
type MockCryptoProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockCryptoProcessorMockRecorder
}

// MockCryptoProcessorMockRecorder is the mock recorder for MockCryptoProcessor.
type MockCryptoProcessorMockRecorder struct {
	mock *MockCryptoProcessor
}

// NewMockCryptoProcessor creates a new mock instance.
func NewMockCryptoProcessor(ctrl *gomock.Controller) *MockCryptoProcessor {
	mock := &MockCryptoProcessor{ctrl: ctrl}
	mock.recorder = &MockCryptoProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptoProcessor) EXPECT() *MockCryptoProcessorMockRecorder {
	return m.recorder
}

// BytesToPrivateKey mocks base method.
func (m *MockCryptoProcessor) BytesToPrivateKey(arg0 []byte) (*rsa.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BytesToPrivateKey", arg0)
	ret0, _ := ret[0].(*rsa.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BytesToPrivateKey indicates an expected call of BytesToPrivateKey.
func (mr *MockCryptoProcessorMockRecorder) BytesToPrivateKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesToPrivateKey", reflect.TypeOf((*MockCryptoProcessor)(nil).BytesToPrivateKey), arg0)
}

// DecryptWithMasterKey mocks base method.
func (m *MockCryptoProcessor) DecryptWithMasterKey(ciphertext, mk []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptWithMasterKey", ciphertext, mk)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptWithMasterKey indicates an expected call of DecryptWithMasterKey.
func (mr *MockCryptoProcessorMockRecorder) DecryptWithMasterKey(ciphertext, mk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptWithMasterKey", reflect.TypeOf((*MockCryptoProcessor)(nil).DecryptWithMasterKey), ciphertext, mk)
}

// DecryptWithPrivateKey mocks base method.
func (m *MockCryptoProcessor) DecryptWithPrivateKey(arg0 []byte, arg1 *rsa.PrivateKey) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptWithPrivateKey", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptWithPrivateKey indicates an expected call of DecryptWithPrivateKey.
func (mr *MockCryptoProcessorMockRecorder) DecryptWithPrivateKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptWithPrivateKey", reflect.TypeOf((*MockCryptoProcessor)(nil).DecryptWithPrivateKey), arg0, arg1)
}

// EncryptWithMasterKey mocks base method.
func (m *MockCryptoProcessor) EncryptWithMasterKey(plaintext, mk []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptWithMasterKey", plaintext, mk)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptWithMasterKey indicates an expected call of EncryptWithMasterKey.
func (mr *MockCryptoProcessorMockRecorder) EncryptWithMasterKey(plaintext, mk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptWithMasterKey", reflect.TypeOf((*MockCryptoProcessor)(nil).EncryptWithMasterKey), plaintext, mk)
}
