// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/proto/records/records.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uuid        *string                `protobuf:"bytes,1,opt,name=uuid"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Kind        *string                `protobuf:"bytes,3,opt,name=kind"`
	xxx_hidden_Payload     []byte                 `protobuf:"bytes,4,opt,name=payload"`
	xxx_hidden_Metadata    []byte                 `protobuf:"bytes,5,opt,name=metadata"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Record) GetUuid() string {
	if x != nil {
		if x.xxx_hidden_Uuid != nil {
			return *x.xxx_hidden_Uuid
		}
		return ""
	}
	return ""
}

func (x *Record) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Record) GetKind() string {
	if x != nil {
		if x.xxx_hidden_Kind != nil {
			return *x.xxx_hidden_Kind
		}
		return ""
	}
	return ""
}

func (x *Record) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *Record) GetMetadata() []byte {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Record) SetUuid(v string) {
	x.xxx_hidden_Uuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Record) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Record) SetKind(v string) {
	x.xxx_hidden_Kind = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Record) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Record) SetMetadata(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Metadata = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Record) HasUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Record) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Record) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Record) HasPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Record) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Record) ClearUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Uuid = nil
}

func (x *Record) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Record) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Kind = nil
}

func (x *Record) ClearPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Payload = nil
}

func (x *Record) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Metadata = nil
}

type Record_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uuid     *string
	Name     *string
	Kind     *string
	Payload  []byte
	Metadata []byte
}

func (b0 Record_builder) Build() *Record {
	m0 := &Record{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Uuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Uuid = b.Uuid
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Kind = b.Kind
	}
	if b.Payload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Payload = b.Payload
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Metadata = b.Metadata
	}
	return m0
}

type AddRecordRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Record *Record                `protobuf:"bytes,1,opt,name=record"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddRecordRequest) Reset() {
	*x = AddRecordRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordRequest) ProtoMessage() {}

func (x *AddRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.xxx_hidden_Record
	}
	return nil
}

func (x *AddRecordRequest) SetRecord(v *Record) {
	x.xxx_hidden_Record = v
}

func (x *AddRecordRequest) HasRecord() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Record != nil
}

func (x *AddRecordRequest) ClearRecord() {
	x.xxx_hidden_Record = nil
}

type AddRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Record *Record
}

func (b0 AddRecordRequest_builder) Build() *AddRecordRequest {
	m0 := &AddRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Record = b.Record
	return m0
}

type UpdateRecordRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Record *Record                `protobuf:"bytes,1,opt,name=record"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.xxx_hidden_Record
	}
	return nil
}

func (x *UpdateRecordRequest) SetRecord(v *Record) {
	x.xxx_hidden_Record = v
}

func (x *UpdateRecordRequest) HasRecord() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Record != nil
}

func (x *UpdateRecordRequest) ClearRecord() {
	x.xxx_hidden_Record = nil
}

type UpdateRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Record *Record
}

func (b0 UpdateRecordRequest_builder) Build() *UpdateRecordRequest {
	m0 := &UpdateRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Record = b.Record
	return m0
}

type GetRecordRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uuid        *string                `protobuf:"bytes,1,opt,name=uuid"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRecordRequest) GetUuid() string {
	if x != nil {
		if x.xxx_hidden_Uuid != nil {
			return *x.xxx_hidden_Uuid
		}
		return ""
	}
	return ""
}

func (x *GetRecordRequest) SetUuid(v string) {
	x.xxx_hidden_Uuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetRecordRequest) HasUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetRecordRequest) ClearUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Uuid = nil
}

type GetRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uuid *string
}

func (b0 GetRecordRequest_builder) Build() *GetRecordRequest {
	m0 := &GetRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Uuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Uuid = b.Uuid
	}
	return m0
}

type DeleteRecordRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uuid        *string                `protobuf:"bytes,1,opt,name=uuid"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRecordRequest) GetUuid() string {
	if x != nil {
		if x.xxx_hidden_Uuid != nil {
			return *x.xxx_hidden_Uuid
		}
		return ""
	}
	return ""
}

func (x *DeleteRecordRequest) SetUuid(v string) {
	x.xxx_hidden_Uuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteRecordRequest) HasUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteRecordRequest) ClearUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Uuid = nil
}

type DeleteRecordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Uuid *string
}

func (b0 DeleteRecordRequest_builder) Build() *DeleteRecordRequest {
	m0 := &DeleteRecordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Uuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Uuid = b.Uuid
	}
	return m0
}

type GetRecordResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Record *Record                `protobuf:"bytes,1,opt,name=record"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.xxx_hidden_Record
	}
	return nil
}

func (x *GetRecordResponse) SetRecord(v *Record) {
	x.xxx_hidden_Record = v
}

func (x *GetRecordResponse) HasRecord() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Record != nil
}

func (x *GetRecordResponse) ClearRecord() {
	x.xxx_hidden_Record = nil
}

type GetRecordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Record *Record
}

func (b0 GetRecordResponse_builder) Build() *GetRecordResponse {
	m0 := &GetRecordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Record = b.Record
	return m0
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListRecordsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListRecordsRequest_builder) Build() *ListRecordsRequest {
	m0 := &ListRecordsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListRecordsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Records *[]*Record             `protobuf:"bytes,1,rep,name=records"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRecordsResponse) GetRecords() []*Record {
	if x != nil {
		if x.xxx_hidden_Records != nil {
			return *x.xxx_hidden_Records
		}
	}
	return nil
}

func (x *ListRecordsResponse) SetRecords(v []*Record) {
	x.xxx_hidden_Records = &v
}

type ListRecordsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Records []*Record
}

func (b0 ListRecordsResponse_builder) Build() *ListRecordsResponse {
	m0 := &ListRecordsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Records = &b.Records
	return m0
}

var File_pkg_proto_records_records_proto protoreflect.FileDescriptor

const file_pkg_proto_records_records_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/records/records.proto\x12\arecords\x1a\x1bgoogle/protobuf/empty.proto\x1a!google/protobuf/go_features.proto\"z\n" +
	"\x06Record\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\fR\bmetadata\";\n" +
	"\x10AddRecordRequest\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.records.RecordR\x06record\">\n" +
	"\x13UpdateRecordRequest\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.records.RecordR\x06record\"&\n" +
	"\x10GetRecordRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\")\n" +
	"\x13DeleteRecordRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"<\n" +
	"\x11GetRecordResponse\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.records.RecordR\x06record\"\x14\n" +
	"\x12ListRecordsRequest\"@\n" +
	"\x13ListRecordsResponse\x12)\n" +
	"\arecords\x18\x01 \x03(\v2\x0f.records.RecordR\arecords2\xe3\x02\n" +
	"\aRecords\x12>\n" +
	"\tAddRecord\x12\x19.records.AddRecordRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fUpdateRecord\x12\x1c.records.UpdateRecordRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fDeleteRecord\x12\x1c.records.DeleteRecordRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\tGetRecord\x12\x19.records.GetRecordRequest\x1a\x1a.records.GetRecordResponse\x12H\n" +
	"\vListRecords\x12\x1b.records.ListRecordsRequest\x1a\x1c.records.ListRecordsResponseB\x17Z\rrecords/proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_pkg_proto_records_records_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_records_records_proto_goTypes = []any{
	(*Record)(nil),              // 0: records.Record
	(*AddRecordRequest)(nil),    // 1: records.AddRecordRequest
	(*UpdateRecordRequest)(nil), // 2: records.UpdateRecordRequest
	(*GetRecordRequest)(nil),    // 3: records.GetRecordRequest
	(*DeleteRecordRequest)(nil), // 4: records.DeleteRecordRequest
	(*GetRecordResponse)(nil),   // 5: records.GetRecordResponse
	(*ListRecordsRequest)(nil),  // 6: records.ListRecordsRequest
	(*ListRecordsResponse)(nil), // 7: records.ListRecordsResponse
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_pkg_proto_records_records_proto_depIdxs = []int32{
	0, // 0: records.AddRecordRequest.record:type_name -> records.Record
	0, // 1: records.UpdateRecordRequest.record:type_name -> records.Record
	0, // 2: records.GetRecordResponse.record:type_name -> records.Record
	0, // 3: records.ListRecordsResponse.records:type_name -> records.Record
	1, // 4: records.Records.AddRecord:input_type -> records.AddRecordRequest
	2, // 5: records.Records.UpdateRecord:input_type -> records.UpdateRecordRequest
	4, // 6: records.Records.DeleteRecord:input_type -> records.DeleteRecordRequest
	3, // 7: records.Records.GetRecord:input_type -> records.GetRecordRequest
	6, // 8: records.Records.ListRecords:input_type -> records.ListRecordsRequest
	8, // 9: records.Records.AddRecord:output_type -> google.protobuf.Empty
	8, // 10: records.Records.UpdateRecord:output_type -> google.protobuf.Empty
	8, // 11: records.Records.DeleteRecord:output_type -> google.protobuf.Empty
	5, // 12: records.Records.GetRecord:output_type -> records.GetRecordResponse
	7, // 13: records.Records.ListRecords:output_type -> records.ListRecordsResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_records_records_proto_init() }
func file_pkg_proto_records_records_proto_init() {
	if File_pkg_proto_records_records_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_records_records_proto_rawDesc), len(file_pkg_proto_records_records_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_records_records_proto_goTypes,
		DependencyIndexes: file_pkg_proto_records_records_proto_depIdxs,
		MessageInfos:      file_pkg_proto_records_records_proto_msgTypes,
	}.Build()
	File_pkg_proto_records_records_proto = out.File
	file_pkg_proto_records_records_proto_goTypes = nil
	file_pkg_proto_records_records_proto_depIdxs = nil
}
