// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/proto/records/records.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Kind          *string                `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,5,opt,name=metadata" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_pkg_proto_records_records_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *Record) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Record) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *Record) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Record) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AddRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecordRequest) Reset() {
	*x = AddRecordRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordRequest) ProtoMessage() {}

func (x *AddRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordRequest.ProtoReflect.Descriptor instead.
func (*AddRecordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_records_records_proto_rawDescGZIP(), []int{1}
}

func (x *AddRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_records_records_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_records_records_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecordRequest) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_records_records_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRecordRequest) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

type GetRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_records_records_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_records_records_proto_rawDescGZIP(), []int{6}
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_pkg_proto_records_records_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_records_records_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_records_records_proto_rawDescGZIP(), []int{7}
}

func (x *ListRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_pkg_proto_records_records_proto protoreflect.FileDescriptor

const file_pkg_proto_records_records_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/records/records.proto\x12\arecords\x1a\x1bgoogle/protobuf/empty.proto\"z\n" +
	"\x06Record\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\fR\bmetadata\";\n" +
	"\x10AddRecordRequest\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.records.RecordR\x06record\">\n" +
	"\x13UpdateRecordRequest\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.records.RecordR\x06record\"&\n" +
	"\x10GetRecordRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\")\n" +
	"\x13DeleteRecordRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"<\n" +
	"\x11GetRecordResponse\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.records.RecordR\x06record\"\x14\n" +
	"\x12ListRecordsRequest\"@\n" +
	"\x13ListRecordsResponse\x12)\n" +
	"\arecords\x18\x01 \x03(\v2\x0f.records.RecordR\arecords2\xe3\x02\n" +
	"\aRecords\x12>\n" +
	"\tAddRecord\x12\x19.records.AddRecordRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fUpdateRecord\x12\x1c.records.UpdateRecordRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fDeleteRecord\x12\x1c.records.DeleteRecordRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\tGetRecord\x12\x19.records.GetRecordRequest\x1a\x1a.records.GetRecordResponse\x12H\n" +
	"\vListRecords\x12\x1b.records.ListRecordsRequest\x1a\x1c.records.ListRecordsResponseB\x0fZ\rrecords/protob\beditionsp\xe8\a"

var (
	file_pkg_proto_records_records_proto_rawDescOnce sync.Once
	file_pkg_proto_records_records_proto_rawDescData []byte
)

func file_pkg_proto_records_records_proto_rawDescGZIP() []byte {
	file_pkg_proto_records_records_proto_rawDescOnce.Do(func() {
		file_pkg_proto_records_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_records_records_proto_rawDesc), len(file_pkg_proto_records_records_proto_rawDesc)))
	})
	return file_pkg_proto_records_records_proto_rawDescData
}

var file_pkg_proto_records_records_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_records_records_proto_goTypes = []any{
	(*Record)(nil),              // 0: records.Record
	(*AddRecordRequest)(nil),    // 1: records.AddRecordRequest
	(*UpdateRecordRequest)(nil), // 2: records.UpdateRecordRequest
	(*GetRecordRequest)(nil),    // 3: records.GetRecordRequest
	(*DeleteRecordRequest)(nil), // 4: records.DeleteRecordRequest
	(*GetRecordResponse)(nil),   // 5: records.GetRecordResponse
	(*ListRecordsRequest)(nil),  // 6: records.ListRecordsRequest
	(*ListRecordsResponse)(nil), // 7: records.ListRecordsResponse
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_pkg_proto_records_records_proto_depIdxs = []int32{
	0, // 0: records.AddRecordRequest.record:type_name -> records.Record
	0, // 1: records.UpdateRecordRequest.record:type_name -> records.Record
	0, // 2: records.GetRecordResponse.record:type_name -> records.Record
	0, // 3: records.ListRecordsResponse.records:type_name -> records.Record
	1, // 4: records.Records.AddRecord:input_type -> records.AddRecordRequest
	2, // 5: records.Records.UpdateRecord:input_type -> records.UpdateRecordRequest
	4, // 6: records.Records.DeleteRecord:input_type -> records.DeleteRecordRequest
	3, // 7: records.Records.GetRecord:input_type -> records.GetRecordRequest
	6, // 8: records.Records.ListRecords:input_type -> records.ListRecordsRequest
	8, // 9: records.Records.AddRecord:output_type -> google.protobuf.Empty
	8, // 10: records.Records.UpdateRecord:output_type -> google.protobuf.Empty
	8, // 11: records.Records.DeleteRecord:output_type -> google.protobuf.Empty
	5, // 12: records.Records.GetRecord:output_type -> records.GetRecordResponse
	7, // 13: records.Records.ListRecords:output_type -> records.ListRecordsResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_records_records_proto_init() }
func file_pkg_proto_records_records_proto_init() {
	if File_pkg_proto_records_records_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_records_records_proto_rawDesc), len(file_pkg_proto_records_records_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_records_records_proto_goTypes,
		DependencyIndexes: file_pkg_proto_records_records_proto_depIdxs,
		MessageInfos:      file_pkg_proto_records_records_proto_msgTypes,
	}.Build()
	File_pkg_proto_records_records_proto = out.File
	file_pkg_proto_records_records_proto_goTypes = nil
	file_pkg_proto_records_records_proto_depIdxs = nil
}
