// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/app/device/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	rsa "crypto/rsa"
	reflect "reflect"

	crypto "github.com/frolmr/GophKeeper/internal/client/crypto"
	domain "github.com/frolmr/GophKeeper/internal/client/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockConnector is a mock of Connector interface.
type MockConnector struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorMockRecorder
}

// MockConnectorMockRecorder is the mock recorder for MockConnector.
type MockConnectorMockRecorder struct {
	mock *MockConnector
}

// NewMockConnector creates a new mock instance.
func NewMockConnector(ctrl *gomock.Controller) *MockConnector {
	mock := &MockConnector{ctrl: ctrl}
	mock.recorder = &MockConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnector) EXPECT() *MockConnectorMockRecorder {
	return m.recorder
}

// SendAddDeviceRequest mocks base method.
func (m *MockConnector) SendAddDeviceRequest(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAddDeviceRequest", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAddDeviceRequest indicates an expected call of SendAddDeviceRequest.
func (mr *MockConnectorMockRecorder) SendAddDeviceRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAddDeviceRequest", reflect.TypeOf((*MockConnector)(nil).SendAddDeviceRequest), arg0)
}

// SendApproveDeviceRequest mocks base method.
func (m *MockConnector) SendApproveDeviceRequest(id string, mk []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendApproveDeviceRequest", id, mk)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendApproveDeviceRequest indicates an expected call of SendApproveDeviceRequest.
func (mr *MockConnectorMockRecorder) SendApproveDeviceRequest(id, mk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendApproveDeviceRequest", reflect.TypeOf((*MockConnector)(nil).SendApproveDeviceRequest), id, mk)
}

// SendGetDeviceMKRequest mocks base method.
func (m *MockConnector) SendGetDeviceMKRequest() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendGetDeviceMKRequest")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendGetDeviceMKRequest indicates an expected call of SendGetDeviceMKRequest.
func (mr *MockConnectorMockRecorder) SendGetDeviceMKRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendGetDeviceMKRequest", reflect.TypeOf((*MockConnector)(nil).SendGetDeviceMKRequest))
}

// SendGetDevicePKRequest mocks base method.
func (m *MockConnector) SendGetDevicePKRequest(id string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendGetDevicePKRequest", id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendGetDevicePKRequest indicates an expected call of SendGetDevicePKRequest.
func (mr *MockConnectorMockRecorder) SendGetDevicePKRequest(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendGetDevicePKRequest", reflect.TypeOf((*MockConnector)(nil).SendGetDevicePKRequest), id)
}

// SendListDevicesRequest mocks base method.
func (m *MockConnector) SendListDevicesRequest() ([]domain.DeviceOnServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendListDevicesRequest")
	ret0, _ := ret[0].([]domain.DeviceOnServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendListDevicesRequest indicates an expected call of SendListDevicesRequest.
func (mr *MockConnectorMockRecorder) SendListDevicesRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendListDevicesRequest", reflect.TypeOf((*MockConnector)(nil).SendListDevicesRequest))
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ReadPrivateKey mocks base method.
func (m *MockRepository) ReadPrivateKey() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPrivateKey")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPrivateKey indicates an expected call of ReadPrivateKey.
func (mr *MockRepositoryMockRecorder) ReadPrivateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPrivateKey", reflect.TypeOf((*MockRepository)(nil).ReadPrivateKey))
}

// SavePrivateKey mocks base method.
func (m *MockRepository) SavePrivateKey(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePrivateKey", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePrivateKey indicates an expected call of SavePrivateKey.
func (mr *MockRepositoryMockRecorder) SavePrivateKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePrivateKey", reflect.TypeOf((*MockRepository)(nil).SavePrivateKey), arg0)
}

// MockCryptoProcessor is a mock of CryptoProcessor interface.
type MockCryptoProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockCryptoProcessorMockRecorder
}

// MockCryptoProcessorMockRecorder is the mock recorder for MockCryptoProcessor.
type MockCryptoProcessorMockRecorder struct {
	mock *MockCryptoProcessor
}

// NewMockCryptoProcessor creates a new mock instance.
func NewMockCryptoProcessor(ctrl *gomock.Controller) *MockCryptoProcessor {
	mock := &MockCryptoProcessor{ctrl: ctrl}
	mock.recorder = &MockCryptoProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptoProcessor) EXPECT() *MockCryptoProcessorMockRecorder {
	return m.recorder
}

// BytesToPrivateKey mocks base method.
func (m *MockCryptoProcessor) BytesToPrivateKey(arg0 []byte) (*rsa.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BytesToPrivateKey", arg0)
	ret0, _ := ret[0].(*rsa.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BytesToPrivateKey indicates an expected call of BytesToPrivateKey.
func (mr *MockCryptoProcessorMockRecorder) BytesToPrivateKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesToPrivateKey", reflect.TypeOf((*MockCryptoProcessor)(nil).BytesToPrivateKey), arg0)
}

// BytesToPublicKey mocks base method.
func (m *MockCryptoProcessor) BytesToPublicKey(arg0 []byte) (*rsa.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BytesToPublicKey", arg0)
	ret0, _ := ret[0].(*rsa.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BytesToPublicKey indicates an expected call of BytesToPublicKey.
func (mr *MockCryptoProcessorMockRecorder) BytesToPublicKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesToPublicKey", reflect.TypeOf((*MockCryptoProcessor)(nil).BytesToPublicKey), arg0)
}

// DecryptWithPrivateKey mocks base method.
func (m *MockCryptoProcessor) DecryptWithPrivateKey(arg0 []byte, arg1 *rsa.PrivateKey) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptWithPrivateKey", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptWithPrivateKey indicates an expected call of DecryptWithPrivateKey.
func (mr *MockCryptoProcessorMockRecorder) DecryptWithPrivateKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptWithPrivateKey", reflect.TypeOf((*MockCryptoProcessor)(nil).DecryptWithPrivateKey), arg0, arg1)
}

// EncryptWithPublicKey mocks base method.
func (m *MockCryptoProcessor) EncryptWithPublicKey(arg0 []byte, arg1 *rsa.PublicKey) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptWithPublicKey", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptWithPublicKey indicates an expected call of EncryptWithPublicKey.
func (mr *MockCryptoProcessorMockRecorder) EncryptWithPublicKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptWithPublicKey", reflect.TypeOf((*MockCryptoProcessor)(nil).EncryptWithPublicKey), arg0, arg1)
}

// GenerateDeviceKey mocks base method.
func (m *MockCryptoProcessor) GenerateDeviceKey() (*crypto.DeviceKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDeviceKey")
	ret0, _ := ret[0].(*crypto.DeviceKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDeviceKey indicates an expected call of GenerateDeviceKey.
func (mr *MockCryptoProcessorMockRecorder) GenerateDeviceKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDeviceKey", reflect.TypeOf((*MockCryptoProcessor)(nil).GenerateDeviceKey))
}

// PrivateKeyToBytes mocks base method.
func (m *MockCryptoProcessor) PrivateKeyToBytes(arg0 *rsa.PrivateKey) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateKeyToBytes", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrivateKeyToBytes indicates an expected call of PrivateKeyToBytes.
func (mr *MockCryptoProcessorMockRecorder) PrivateKeyToBytes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateKeyToBytes", reflect.TypeOf((*MockCryptoProcessor)(nil).PrivateKeyToBytes), arg0)
}

// PublicKeyToBytes mocks base method.
func (m *MockCryptoProcessor) PublicKeyToBytes(arg0 *rsa.PublicKey) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicKeyToBytes", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicKeyToBytes indicates an expected call of PublicKeyToBytes.
func (mr *MockCryptoProcessorMockRecorder) PublicKeyToBytes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicKeyToBytes", reflect.TypeOf((*MockCryptoProcessor)(nil).PublicKeyToBytes), arg0)
}
