// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/api/handlers/users_handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/frolmr/GophKeeper/internal/server/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUsersRepository is a mock of UsersRepository interface.
type MockUsersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsersRepositoryMockRecorder
}

// MockUsersRepositoryMockRecorder is the mock recorder for MockUsersRepository.
type MockUsersRepositoryMockRecorder struct {
	mock *MockUsersRepository
}

// NewMockUsersRepository creates a new mock instance.
func NewMockUsersRepository(ctrl *gomock.Controller) *MockUsersRepository {
	mock := &MockUsersRepository{ctrl: ctrl}
	mock.recorder = &MockUsersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersRepository) EXPECT() *MockUsersRepositoryMockRecorder {
	return m.recorder
}

// CreateUserAndDevice mocks base method.
func (m *MockUsersRepository) CreateUserAndDevice(ctx context.Context, email, password, deviceName, deviceID string, maskterKey []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAndDevice", ctx, email, password, deviceName, deviceID, maskterKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserAndDevice indicates an expected call of CreateUserAndDevice.
func (mr *MockUsersRepositoryMockRecorder) CreateUserAndDevice(ctx, email, password, deviceName, deviceID, maskterKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAndDevice", reflect.TypeOf((*MockUsersRepository)(nil).CreateUserAndDevice), ctx, email, password, deviceName, deviceID, maskterKey)
}

// GetDeviceByUserUUIDAndID mocks base method.
func (m *MockUsersRepository) GetDeviceByUserUUIDAndID(ctx context.Context, name string, userUUID uuid.UUID) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByUserUUIDAndID", ctx, name, userUUID)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByUserUUIDAndID indicates an expected call of GetDeviceByUserUUIDAndID.
func (mr *MockUsersRepositoryMockRecorder) GetDeviceByUserUUIDAndID(ctx, name, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByUserUUIDAndID", reflect.TypeOf((*MockUsersRepository)(nil).GetDeviceByUserUUIDAndID), ctx, name, userUUID)
}

// GetUserByEmail mocks base method.
func (m *MockUsersRepository) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUsersRepositoryMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUsersRepository)(nil).GetUserByEmail), ctx, email)
}

// MockJWTManager is a mock of JWTManager interface.
type MockJWTManager struct {
	ctrl     *gomock.Controller
	recorder *MockJWTManagerMockRecorder
}

// MockJWTManagerMockRecorder is the mock recorder for MockJWTManager.
type MockJWTManagerMockRecorder struct {
	mock *MockJWTManager
}

// NewMockJWTManager creates a new mock instance.
func NewMockJWTManager(ctrl *gomock.Controller) *MockJWTManager {
	mock := &MockJWTManager{ctrl: ctrl}
	mock.recorder = &MockJWTManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTManager) EXPECT() *MockJWTManagerMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockJWTManager) GenerateAccessToken(userUUID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJWTManagerMockRecorder) GenerateAccessToken(userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJWTManager)(nil).GenerateAccessToken), userUUID)
}
